# Generated by Django 4.0.1 on 2022-05-12 03:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cache_explorer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CookieStand',
            new_name='CacheExplorer',
        ),
    ]
