# Generated by Django 4.0.1 on 2022-05-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cache_explorer', '0002_rename_cookiestand_cacheexplorer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cacheexplorer',
            name='average_cookies_per_sale',
        ),
        migrations.RemoveField(
            model_name='cacheexplorer',
            name='hourly_sales',
        ),
        migrations.RemoveField(
            model_name='cacheexplorer',
            name='maximum_customers_per_hour',
        ),
        migrations.RemoveField(
            model_name='cacheexplorer',
            name='minimum_customers_per_hour',
        ),
    ]
