# Generated by Django 4.0.1 on 2022-05-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache_explorer', '0004_cache_delete_cacheexplorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cache',
            name='title',
            field=models.CharField(default='ADD TITLE', max_length=256),
        ),
    ]
