# Generated by Django 4.0.1 on 2022-05-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cache_explorer', '0005_cache_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='title',
            field=models.CharField(default='TITLE', max_length=256),
        ),
    ]
